<?php
$messages = array();
$messages['alias'] = 'alias';
$messages['sigvalid'] = 'Hiteles digitális aláírás: $sender. Hitelesítve $issuer által.';
$messages['sigunverified'] = 'Hiteles digitális aláírás (hibás bizonyítvánnyal): $sender.  Hitelesítve $issuer által.';
$messages['siginvalid'] = 'Hibás digitális aláírás.';
$messages['smime_encrypt_label'] = 'Levél titkosítása S/MIME segítségével';
$messages['smime_sign_label'] = 'Levél aláírása S/MIME segítségével';

$labels = array();
$labels['smime_continue_unencrypted'] = 'Folytatás kódolás nélkül?';
$labels['smime_get_password'] = 'Jelszó: ';
?>
